<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class RemoveModule extends Command
{
    protected $signature = 'remove:module {name} {--admin} {--front}';
    protected $description = 'Remove all files generated by make:module command';

    public function handle()
    {
        $name = ucfirst($this->argument('name'));
        $type = $this->option('admin') ? 'Admin' : ($this->option('front') ? 'front' : null);

        if (!$type) {
            $this->error("Please specify --admin or --front.");
            return;
        }

        // Define all paths for files to be deleted
        $paths = [
            app_path("Models/{$name}.php"),
            app_path("Http/Controllers/$type/{$name}Controller.php"),
            app_path("Http/Requests/$type/{$name}Request.php"),
            app_path("Http/Resources/$type/{$name}Resource.php"),
            app_path("Http/Resources/$type/{$name}Collection.php"),
            app_path("Repositories/{$name}Repository.php"),
        ];

        // Find migration file dynamically
        $migrationFile = collect(File::files(database_path('migrations')))
            ->first(fn ($file) => Str::contains($file->getFilename(), 'create_' . Str::snake(Str::plural($name)) . '_table.php'));

        if ($migrationFile) {
            $paths[] = $migrationFile->getPathname();
        }

        // Loop through paths and delete files if they exist
        foreach ($paths as $path) {
            if (File::exists($path)) {
                File::delete($path);
                $this->info("Deleted: " . str_replace(base_path(), '', $path));
            } else {
                $this->warn("Not found: " . str_replace(base_path(), '', $path));
            }
        }

        $this->info("Module $name has been successfully removed!");
    }
}
